# Generated by Django 6.0.2 on 2026-04-24 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_api', '0002_road_delete_roadsegment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='road',
            options={'verbose_name': 'Запись состояния дороги', 'verbose_name_plural': 'Записи состояния дорог'},
        ),
        migrations.AddField(
            model_name='road',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='road',
            name='humidity',
            field=models.IntegerField(default=0, verbose_name='Влажность'),
        ),
        migrations.AddField(
            model_name='road',
            name='wind_speed',
            field=models.FloatField(default=0.0, verbose_name='Скорость ветра'),
        ),
        migrations.AlterField(
            model_name='road',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата замера'),
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Координаты/Название'),
        ),
        migrations.AlterField(
            model_name='road',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='road',
            name='temp',
            field=models.IntegerField(verbose_name='Температура'),
        ),
    ]
