# Generated by Django 6.0.2 on 2026-04-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_api', '0003_alter_road_options_road_author_road_humidity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='road',
            options={},
        ),
        migrations.RemoveField(
            model_name='road',
            name='author',
        ),
        migrations.RemoveField(
            model_name='road',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='road',
            name='wind_speed',
        ),
        migrations.AlterField(
            model_name='road',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='road',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='road',
            name='temp',
            field=models.IntegerField(),
        ),
    ]
