# Generated by Django 6.0.2 on 2026-04-24 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_api', '0004_alter_road_options_remove_road_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='road',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата замера'),
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Участок дороги'),
        ),
        migrations.AlterField(
            model_name='road',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='road',
            name='temp',
            field=models.IntegerField(verbose_name='Температура'),
        ),
    ]
