# Generated by Django 6.0.2 on 2026-04-24 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_api', '0005_road_author_alter_road_created_at_alter_road_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('warning_type', models.CharField(choices=[('ГОЛОЛЕД', 'Гололед'), ('НАВОДНЕНИЕ', 'Наводнение'), ('БУРЯ', 'Буря'), ('АВАРИЯ', 'Авария'), ('ПЕРЕКРЫТИЕ', 'Перекрытие трассы')], max_length=50, verbose_name='Тип предупреждения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('severity', models.IntegerField(choices=[(1, 'Низкая'), (2, 'Средняя'), (3, 'Высокая')], default=1, verbose_name='Уровень опасности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения')),
            ],
        ),
        migrations.AddField(
            model_name='road',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='road',
            name='ice_probability',
            field=models.IntegerField(default=0, verbose_name='Вероятность гололеда (%)'),
        ),
        migrations.AddField(
            model_name='road',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='road',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='road',
            name='status',
            field=models.CharField(choices=[('ОТКРЫТА', 'Открыта'), ('ЗАКРЫТА', 'Закрыта'), ('ЧАСТИЧНО ОГРАНИЧЕНА', 'Частично ограничена'), ('РЕМОНТ', 'Ремонт'), ('ДТП/ЗАТОР', 'ДТП / затор'), ('ОПАСНО', 'Опасный участок')], default='ОТКРЫТА', max_length=50, verbose_name='Состояние'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CLOSURE', 'Перекрытие трассы'), ('WEATHER', 'Погода'), ('ACCIDENT', 'Авария'), ('ROUTE', 'Маршрут')], max_length=50, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.FloatField(verbose_name='Начало - широта')),
                ('start_lng', models.FloatField(verbose_name='Начало - долгота')),
                ('end_lat', models.FloatField(verbose_name='Конец - широта')),
                ('end_lng', models.FloatField(verbose_name='Конец - долгота')),
                ('name', models.CharField(max_length=255, verbose_name='Имя маршрута')),
                ('waypoints', models.JSONField(default=list, verbose_name='Промежуточные точки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
