# Generated by Django 6.0.2 on 2026-04-24 15:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_api', '0006_emergencywarning_road_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencywarning',
            options={'verbose_name': 'Экстренное предупреждение', 'verbose_name_plural': 'Экстренные предупреждения'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='road',
            options={'verbose_name': 'Участок дороги', 'verbose_name_plural': 'Участки дорог'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.RemoveField(
            model_name='emergencywarning',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='emergencywarning',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='emergencywarning',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='emergencywarning',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='road',
            name='ice_probability',
        ),
        migrations.RemoveField(
            model_name='road',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='road',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='road',
            name='temp',
        ),
        migrations.AddField(
            model_name='emergencywarning',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='emergencywarning',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата разрешения'),
        ),
        migrations.AddField(
            model_name='emergencywarning',
            name='road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='road_api.road', verbose_name='Участок дороги'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='road_api.road', verbose_name='Связанная дорога'),
        ),
        migrations.AddField(
            model_name='road',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='road_api.route', verbose_name='Маршрут'),
        ),
        migrations.AddField(
            model_name='road',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='emergencywarning',
            name='severity',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=50, verbose_name='Уровень серьезности'),
        ),
        migrations.AlterField(
            model_name='emergencywarning',
            name='warning_type',
            field=models.CharField(choices=[('accident', 'Авария'), ('traffic_delay', 'Затруднение движения'), ('weather_hazard', 'Опасность из-за погоды'), ('repair_work', 'Ремонтные работы'), ('other', 'Прочее')], max_length=50, verbose_name='Тип предупреждения'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('road_closure', 'Перекрытие трассы'), ('weather_warning', 'Предупреждение о плохой погоде'), ('emergency', 'Аварийное сообщение'), ('repair_work', 'Ремонтные работы'), ('other', 'Прочее')], max_length=50, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='road',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта'), ('partially_restricted', 'Частично ограничена')], default='open', max_length=50, verbose_name='Состояние'),
        ),
        migrations.CreateModel(
            name='DangerousArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danger_type', models.CharField(choices=[('ice', 'Гололёд'), ('snow', 'Снег'), ('flooding', 'Затопление'), ('pothole', 'Яма'), ('debris', 'Обломки'), ('slippery', 'Скользкая дорога'), ('other', 'Прочее')], max_length=50, verbose_name='Тип опасности')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата разрешения')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('road', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dangerous_areas', to='road_api.road', verbose_name='Участок дороги')),
            ],
            options={
                'verbose_name': 'Опасный участок',
                'verbose_name_plural': 'Опасные участки',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(verbose_name='Температура воздуха (°C)')),
                ('precipitation', models.CharField(max_length=50, verbose_name='Осадки')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра (км/ч)')),
                ('visibility', models.FloatField(verbose_name='Видимость (м)')),
                ('ice_probability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Вероятность гололёда (%)')),
                ('mcs_warning', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предупреждение МЧС')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='Время замера')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('road', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='road_api.road', verbose_name='Участок дороги')),
            ],
            options={
                'verbose_name': 'Данные погоды',
                'verbose_name_plural': 'Данные погоды',
            },
        ),
    ]
